# .github/workflows/visual-testing.yml
name: Visual Testing

on:
  workflow_dispatch:
    inputs:
      url_group:
        description: "URL group to test"
        required: true
        type: choice
        options:
          - "adenenergies-main"
          - "adenenergies-zh"
          - "adengroup-main"
          - "adengroup-cn"
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      url_groups: ${{ steps.set-groups.outputs.groups }}
    steps:
      - id: set-groups
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "groups=['${{ github.event.inputs.url_group }}']" >> $GITHUB_OUTPUT
          else
            echo "groups=['adenenergies-main','adenenergies-zh','adengroup-main','adengroup-cn']" >> $GITHUB_OUTPUT
          fi

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        url_group: ${{fromJson(needs.prepare.outputs.url_groups)}}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests for ${{ matrix.url_group }}
        run: node run-tests-ci.js ${{ matrix.url_group }}

      - name: Generate report
        run: node generate-report.js

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.url_group }}
          path: playwright-report/ci
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.url_group }}
          path: test-results/ci
          retention-days: 30

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.url_group }}
          path: screenshots/ci
          retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download playwright report
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          path: public
          merge-multiple: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
